cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    roshan:
      email: dbaldwin@gmail.com
      name: David Baldwin
      password: $2b$12$2em24tVLOqCpAAzibzsqcuLag7kwfZApLevOFYyKym1o1bIffeqMO
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$2em24tVLOqCpAAzibzsqcuLag7kwfZApLevOFYyKym1o1bIffeqMO
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$2em24tVLOqCpAAzibzsqcuLag7kwfZApLevOFYyKym1o1bIffeqMO
    rcouper:
      email: rcouper@gmail.com
      name: Ross Couper
      password: $2b$12$2em24tVLOqCpAAzibzsqcuLag7kwfZApLevOFYyKym1o1bIffeqMO
preauthorized:
  emails:
  - melsby@gmail.com